version: "3.0"

services:

  ##############################################################################
  # タスクコンテナ（ビルドなどの処理をおこなうだけのコンテナ）
  ##############################################################################

  validate-openapi-document:
    image: openapitools/openapi-generator-cli
    hostname: validate-openapi-document
    container_name: validate-openapi-document
    volumes:
      - ./src:/local/src
    command: validate -i /local/src/root.yaml

  generate-openapi-document:
    image: openapitools/openapi-generator-cli
    hostname: generate-openapi-document
    container_name: generate-openapi-document
    volumes:
      - ./src:/local/src
      - ./dist:/local/dist
    command: |
      generate
        -g openapi-yaml
        -i /local/src/root.yaml
        -o /local/dist

  generate-openapi-client:
    image: openapitools/openapi-generator-cli
    hostname: generate-openapi-document
    container_name: generate-openapi-document
    volumes:
      - ./src:/local/src
      - ./client:/local/dist
    command: |
      generate
        -g typescript-axios
        -i /local/src/root.yaml
        -o /local/dist

  generate-openapi-skeleton:
    image: openapitools/openapi-generator-cli
    hostname: generate-openapi-skeleton
    container_name: generate-openapi-skeleton
    volumes:
      - ./dist:/local/src
      - ./skeleton:/local/dist
    command: |
      generate
        -g go-server
        -i /local/src/openapi/openapi.yaml
        -o /local/dist


  ##############################################################################
  # デーモンコンテナ（Web、DBサーバーなどバックグラウンドで常に起動しつづけるコンテナ）
  ##############################################################################

  openapi-mock:
    build:
      context: ./
      dockerfile: Dockerfile.prism
    image: testing-file-generator-mock
    hostname: testing-file-generator-mock
    container_name: testing-file-generator-mock
    ports:
      - "8280:4010"
    volumes:
      - ./dist/openapi:/tmp/dist
    command: mock -d -h 0.0.0.0 /tmp/dist/openapi.yaml
    
  openapi-document:
    build:
      context: ./
      dockerfile: Dockerfile.rapidoc
    image: testing-file-generator-document
    hostname: testing-file-generator-document
    container_name: testing-file-generator-document
    ports:
      - "8380:80"
    volumes:
      - ./dist/openapi/openapi.yaml:/usr/share/nginx/html/openapi.yaml
      - ./rapidoc/index.html:/usr/share/nginx/html/index.html
