version: "3.0"

services:
  testing-file-generator-api:
    build:
      context: ./
      dockerfile: docker/testing-file-generator-api/Dockerfile
    image: testing-file-generator-api
    hostname: testing-file-generator-api
    container_name: testing-file-generator-api
    ports:
      - "8020:8080"

  openapi-document:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./openapi/reference/root.yaml:/usr/share/nginx/html/openapi.yaml
      - ./docs/repidoc/index.html:/usr/share/nginx/html/index.html

  openapi-mock:
    image: stoplight/prism
    ports:
      - "8010:4010"
    volumes:
      - ./openapi:/tmp/dist
    command: mock -d -h 0.0.0.0 /tmp/dist/reference/root.yaml

