/*
 * testing-file-generator
 *
 * テスト用のダミーファイルを生成するAPI
 *
 * API version: 1.0.0
 * Contact: hazuki3417@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	"github.com/hazuki3417/testing-file-generator/openapi"
	"github.com/rs/cors"
)

func main() {
	log.Printf("Server started")

	DevZeroApiService := openapi.NewDevZeroApiService()
	DevZeroApiController := openapi.NewDevZeroApiController(DevZeroApiService)

	router := openapi.NewRouter(DevZeroApiController)
	handler := cors.AllowAll().Handler(router)

	log.Fatal(http.ListenAndServe(":8080", handler))
}
