/*
 * testing-file-generator
 *
 * テスト用のダミーファイルを生成するAPI
 *
 * API version: 1.0.0
 * Contact: hazuki3417@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Dd - 生成するテストデータの情報を指定（1件）
type Dd struct {

	// ファイル名を指定します
	FileName string `json:"fileName"`

	// ファイルサイズを指定します（byte指定）
	Size uint32 `json:"size"`
}
