/*
 * testing-file-generator
 *
 * テスト用のダミーファイルを生成するAPI
 *
 * API version: 1.0.0
 * Contact: hazuki3417@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Dds - 生成するテストデータの情報を指定（n件）
type Dds struct {

	Specs []Dd `json:"specs"`
}
