/*
 * testing-file-generator
 *
 * テスト用のダミーファイルを生成するAPI
 *
 * API version: 1.0.0
 * Contact: hazuki3417@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Error - エラーの情報
type Error struct {

	// クエリパラメータ名
	Key string `json:"key,omitempty"`

	// エラーの理由
	Reason string `json:"reason,omitempty"`
}
