/*
 * testing-file-generator
 *
 * テスト用のダミーファイルを生成するAPI
 *
 * API version: 1.0.0
 * Contact: hazuki3417@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ErrorInfoPosition - エラーの情報（複数データver）
type ErrorInfoPosition struct {

	// エラー内容
	Message string `json:"message"`

	// エラーの情報
	Errors []ErrorPosition `json:"errors"`
}
