openapi: 3.0.3
info:
  version: 1.0.0
  title: testing-file-generator
  description: テスト用のダミーファイルを生成するAPI
  termsOfService: 'https://github.com/hazuki3417/testing-file-generator'
  contact:
    email: hazuki3417@gmail.com
    name: hazuki3417
  license:
    name: MIT
    url: 'https://github.com/hazuki3417/testing-file-generator'
servers:
  - url: 'http://localhost:3100'
    description: API Mockサーバー（stoplight studio）
  - url: 'http://localhost:8280'
    description: API Mockサーバー（container）
  - url: 'http://develop:8280'
    description: API Mockサーバー（development）
  - url: 'http://localhost:8180'
    description: DevelopAPIサーバー (local)
  - url: 'http://develop:8180'
    description: DevelopAPIサーバー (development)
tags:
  - name: /dev/zero
paths:
  /dd:
    post:
      tags:
        - /dev/zero
      summary: ダミーファイルを生成します（1件）
      description: ヌルキャラクタで埋め尽くされたファイルを生成してダウンロードします（1件）
      operationId: post-dd
      responses:
        '204':
          description: No Content
        '400':
          description: リクエストが不正
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInfo'
        '500':
          $ref: '#/components/responses/500-InternalServerError'
        '503':
          $ref: '#/components/responses/503-ServiceUnavailable'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dd'
            examples:
              例1:
                value:
                  fileName: 1kbyte.txt
                  size: 1000
  /dds:
    post:
      tags:
        - /dev/zero
      summary: ダミーファイルを生成します（n件）
      description: ヌルキャラクタで埋め尽くされたファイルを生成してダウンロードします（n件）
      operationId: post-dds
      responses:
        '204':
          description: No Content
        '400':
          description: リクエストが不正
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInfoPosition'
              examples: {}
        '500':
          $ref: '#/components/responses/500-InternalServerError'
        '503':
          $ref: '#/components/responses/503-ServiceUnavailable'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dds'
            examples:
              n件:
                value:
                  specs:
                    - fileName: 3kbyte.txt
                      size: 3000
                    - fileName: 5kbyte.txt
                      size: 5000
              1件:
                value:
                  specs:
                    - fileName: 1kbyte.txt
                      size: 1000
components:
  schemas:
    ErrorInfo:
      type: object
      description: エラーの情報
      properties:
        message:
          $ref: '#/components/schemas/Error-Key-Message'
        errors:
          type: array
          description: エラーの情報
          uniqueItems: true
          items:
            $ref: '#/components/schemas/Error'
      required:
        - message
        - errors
    ErrorInfoPosition:
      type: object
      description: エラーの情報（複数データver）
      properties:
        message:
          $ref: '#/components/schemas/Error-Key-Message'
        errors:
          type: array
          description: エラーの情報
          uniqueItems: true
          items:
            $ref: '#/components/schemas/ErrorPosition'
      required:
        - message
        - errors
    Error:
      type: object
      description: エラーの情報
      properties:
        key:
          type: string
          maxLength: 256
          minLength: 0
          description: クエリパラメータ名
        reason:
          type: string
          maxLength: 256
          minLength: 0
          description: エラーの理由
      required:
        - key
        - reason
    ErrorPosition:
      description: エラーの情報（複数データver）
      allOf:
        - type: object
          properties:
            index:
              type: integer
              minimum: 0
              default: 0
              description: エラーの要素番号
              exclusiveMinimum: false
            depth:
              type: integer
              description: エラーの階層
              default: 0
              minimum: 0
          required:
            - index
            - depth
        - $ref: '#/components/schemas/Error'
    Dd:
      description: 生成するテストデータの情報を指定（1件）
      type: object
      properties:
        fileName:
          type: string
          minLength: 1
          maxLength: 256
          description: ファイル名を指定します
          pattern: '.*\.[a-zA-Z0-9]+$'
        size:
          type: integer
          description: ファイルサイズを指定します（byte指定）
          minimum: 1000
          maximum: 1073741824
          default: 1000
      required:
        - fileName
        - size
    Dds:
      title: Dds
      type: object
      description: 生成するテストデータの情報を指定（n件）
      properties:
        specs:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/Dd'
      required:
        - specs
    Error-Key-Message:
      type: string
      title: Error-Key-Message
      maxLength: 256
      minLength: 0
      description: エラー内容
      default: リクエストが不正です
  parameters: {}
  responses:
    500-InternalServerError:
      description: サーバーエラーが発生
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorInfo'
          example:
            message: サーバーにエラーが発生しました
            errors: []
    503-ServiceUnavailable:
      description: メンテナンス中
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorInfo'
          example:
            message: メンテナンス中です
            errors: []
