name: pr-testing-backend
on:
  pull_request:
    branches: [ feature-backend ]

jobs:
  tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install dependencies
        run: go install

      - name: Testing
        run: make test
