# 概要: バックエンドのリグレッションテストを行うアクション

name: Testing Backend
on:
  # NOTE: PR作成時は常にテストを実行
  pull_request:
    branches: [main, 'release*', 'feature*']
  # NOTE: 機能実装ブランチに変更が発生したときは常にテストを実行
  push:
    branches: ['feature*']
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install dependencies
        run: go install

      - name: Testing
        run: make test
